# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Publish Package to npmjs

on:
  push:
    branches: 
       - main
    tags:
       - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          registry-url: https://registry.npmjs.org/
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
          
      - name: Build
        run: |
         npm ci
         npm run build

      - name: Generate Changelog
        run: npm run release

      - name: Create tag and push to Git
        run: |
         git config user.email "little_hui@foxmail.com"
         git config user.name "eric_chao"
         git push --follow-tags origin main
      - name: Publish To NPM
        run: npm publish
